books/urls.py
from django.urls import path

from books import views

# books:book
app_name = "books"

urlpatterns = [
    path("", views.home, name="home"),  # home
    path("books/search/", views.search, name="search"),
    path("books/category/<int:category_id>/", views.category, name="category"),
    path("books/<int:id>/", views.book, name="book"),  # books
    path("books", views.BookList.as_view(), name="book-list"),
]

django_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("books.urls")),
    path("authors/", include("authors.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

books/models.py
from django.contrib.auth.models import User
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.text import slugify


class Category(models.Model):
    """Representa a categoria de um livro. Ex. literatura
    estrangeira, livro técnico...
    """

    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Book(models.Model):
    """Livros"""

    CONSERVATION_CHOICES = (
        ("Muito Usado", "Muito Usado"),
        ("Usado", "Usado"),
        ("Semi-novo", "Semi-Novo"),
        ("Novo", "Novo"),
    )
    TITULO = models.CharField(max_length=65)
    DESCRICAO = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    AUTOR_DO_LIVRO = models.CharField(max_length=65)
    ANO_DE_PUBLICACAO = models.IntegerField()
    ESTADO_DE_CONSERVACAO = models.CharField(
        max_length=20, choices=CONSERVATION_CHOICES, blank=False, null=False
    )
    IDIOMA = models.CharField(max_length=50)
    EDITORA = models.CharField(max_length=65)
    ISBN = models.IntegerField()
    RESUMO_DA_OBRA = models.TextField() #review
    review_is_html = models.BooleanField(default=False)
    TELEFONE_DO_DOADOR = models.CharField(max_length=15)
    CIDADE_DO_DOADOR = models.CharField(max_length=30)
    EMAIL_DO_DOADOR = models.EmailField(max_length=70, blank=True, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    IMAGEM_DA_CAPA_DO_LIVRO = models.ImageField(
        upload_to="books/covers/%Y/%m/%d/", blank=True, default=""
    )
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True, default=None
    )
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.TITULO


    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.TITULO)}'
            self.slug = slug

        return super().save(*args, **kwargs)

authors/forms/book_form.py
from books.models import Book
from django import forms
from utils.django_forms import add_attr
from collections import defaultdict
from django.core.exceptions import ValidationError



class AuthorBookForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._my_errors = defaultdict(list)
        

        add_attr(self.fields.get('TITULO'), 'class', 'span-2')
        
        
        

    class Meta:
        model = Book
        fields = 'TITULO', 'DESCRICAO', 'AUTOR_DO_LIVRO', \
            'ANO_DE_PUBLICACAO', 'ESTADO_DE_CONSERVACAO', \
            'IDIOMA', 'EDITORA', 'category', \
            'ISBN', 'RESUMO_DA_OBRA','CIDADE_DO_DOADOR', \
            'EMAIL_DO_DOADOR','TELEFONE_DO_DOADOR', 'IMAGEM_DA_CAPA_DO_LIVRO',                
        widgets = {
            'IMAGEM_DA_CAPA_DO_LIVRO' : forms.FileInput(
                attrs= {
                    'class': 'span-2'
                }
            ),
            'IDIOMA': forms.Select(
                choices=(
                    ('Português', 'Português'),
                    ('Inglês', 'Inglês'),
                    ('Espanhol', 'Espanhol'),
                    ('Francês', 'Francês'),
                    ('Alemão', 'Alemão'),
                    ('Italiano', 'Italiano'),
                ),
            ),
        }


    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)
        cd = self.cleaned_data
        TITULO = cd.get('TITULO')
        description = cd.get('DESCRICAO')
        if len(TITULO) < 5:
            self._my_errors['TITULO'].append('Título deve ter ao menos 5 caracteres.')

        if TITULO == description:
            self._my_errors['TITULO'].append('Não pode ser igual a descrição')
            self._my_errors['DESCRICAO'].append('Não pode ser igual ao título')

        if self._my_errors: 
            raise ValidationError(self._my_errors)

        return super_clean

books/views.py
import os

from django.contrib import messages
from django.db.models import Q
from django.http.response import Http404
from django.shortcuts import get_list_or_404, get_object_or_404, render

from utils.books.factory import make_book
from utils.pagination import make_pagination

from .models import Book
from rest_framework import generics
from .serializers import BookSerializer


PER_PAGE = int(os.environ.get("PER_PAGE", 3))

# Api

class BookList(generics.ListCreateAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer



def home(request):
    books = Book.objects.filter(
        is_published=True,
    ).order_by("-id")

    page_obj, pagination_range = make_pagination(request, books, PER_PAGE)

    return render(
        request,
        "books/pages/home.html",
        context={"books": page_obj, "pagination_range": pagination_range
        })


def category(request, category_id):
    books = get_list_or_404(
        Book.objects.filter(
            category__id=category_id,
            is_published=True,
        ).order_by("-id")
    )

    page_obj, pagination_range = make_pagination(request, books, PER_PAGE)

    return render(
        request,
        "books/pages/category.html",
        context={
            "books": page_obj,
            "pagination_range": pagination_range,
            "title": f"{books[0].category.name} - Category | ",
        })


def book(request, id):
    book = get_object_or_404(
        Book,
        pk=id,
        is_published=True,
    )

    return render(
        request,
        "books/pages/book-view.html",
        context={
            "book": book,
            "is_detail_page": True,
        },
    )


def search(request):
    search_term = request.GET.get("q", "").strip()

    if not search_term:
        raise Http404()

    books = Book.objects.filter(
        Q(
            Q(TITULO__icontains=search_term) | Q(DESCRICAO__icontains=search_term),
        ),
        is_published=True,
    ).order_by("-id")

    page_obj, pagination_range = make_pagination(request, books, PER_PAGE)

    #messages.success(request, "Epa, você pesquisou!!!.")
    return render(
        request,
        "books/pages/search.html",
        {
            "page_title": f'Search for "{search_term}" |',
            "search_term": search_term,
            "books": page_obj,
            "pagination_range": pagination_range,
            "additional_url_query": f"&q={search_term}",
        },
    )

books/templates/books/partials/book.html
<div class="book book-list-item">
    {% if book.IMAGEM_DA_CAPA_DO_LIVRO %}
        <div class="book-cover">
            <a href="{% url 'books:book' book.id %}">
                <img src="{{ book.IMAGEM_DA_CAPA_DO_LIVRO.url }}" alt="Imagem Temporária">
            </a>
        </div>
    {% endif %}

    <div class="book-title-container">
        <h2 class="book-title">
            <a href="{% url 'books:book' book.id %}">
            {{ book.TITULO }} 
            </a>
        </h2>
    </div>

    <div class="book-author">        
        <span class="book-author-item">
            <i class="fas fa-user"></i>
            {% if book.author is not None %}
                {% if book.author.first_name %}
                    {{ book.author.first_name }} {{ book.author.last_name }}
                {% else %}
                    {{ book.author.username }}
                {% endif %}
            {% else %}
                Desconhecido
            {% endif %}
        </span>

        <span class="book-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ book.created_at|date:"d/m/Y" }} às {{ book.created_at|date:"H:i" }}
        </span>

        {% if book.category is not None %}
            <span class="book-author-item">
                <a href="{% url 'books:category' book.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ book.category.name }}</span>
                </a>
            </span>
        {% endif %}


    </div>

    <div class="book-content">
        <p> Descrição: {{ book.DESCRICAO }}</p>
        <p>Autor: {{ book.AUTOR_DO_LIVRO}} </p>
    </div>
    <div class="book-meta-container">
    <div class="book-meta book-preparation">
        <h3 class="book-meta-title"><i class="fas fa-solid fa-city"></i> Cidade</h3>
        <div class="book-meta-text">
            {{ book.CIDADE_DO_DOADOR }}
        </div>
    </div>
    <div class="book-meta book-servings">
        <h3 class="book-meta-title"><i class="fas fa-solid fa-city"></i> Estado de Conservação</h3>
        <div class="book-meta-text">
            {{ book.ESTADO_DE_CONSERVACAO }}
        </div>
    </div>
</div>

    {% if is_detail_page is not True %}
        <footer class="book-footer">
            <a class="book-read-more button button-dark button-full-width" href="{% url 'books:book' book.id %}">
                <i class="fas fa-eye"></i>
                <span>Ver mais...</span>
            </a>
        </footer>
    {% endif %}

    {% if is_detail_page is True %}
        <div class="preparation-steps">
            {% if book.preparation_steps_is_html is True %}
                {{ book.preparation_steps|safe }}
                Review: {{ book.RESUMO_DA_OBRA }}
            {% else %}
                <h3>Informações Complementares: </h3>
                {{ book.preparation_steps|linebreaksbr }}
                Review: {{ book.RESUMO_DA_OBRA }} <br><br>
                Editora: {{ book.EDITORA}} <br><br>
                Isbn: {{ book.ISBN}}  <br><br>
                Idioma da obra: {{ book.IDIOMA }} <br><br>
                Contato do doador: <strong> {{ book.EMAIL_DO_DOADOR}} - {{ book.TELEFONE_DO_DOADOR}} <strong>

            {% endif %}
        </div>
    {% endif %}

</div> 

books/templates/books/partials/footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="#" target="_blank" rel="noreferrer noopener">Projeto Integrador - Grupo nr.01</a>
      
    </div>
  
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Django</a>
    </div>
  </footer>

books/templates/books/partials/head.html
{% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
        integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
        integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
        integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'books/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'global/css/styles.css' %}">

books/templates/books/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'books:home' %}">
                <!---P/ Tati: corrigir/atualizar o ícone -->
                <i class="fas fa-solid fa-books"></i>
                <span class="main-logo-text">Livros para Doar</span>
            </a>
        </h1>
    </div>
</header>

books/templates/books/partials/pagination.html
{% if books.has_other_pages %}
  <div class="container pagination">
    <div class="pagination-content">
      {% if pagination_range.first_page_out_of_range %}
        <a class="page-link page-item" href="?page=1{{ additional_url_query }}">1</a>
        <span class="page-item">...</span>
      {% endif %}

      {% for page in pagination_range.pagination %}
        {% if pagination_range.current_page == page %}
          <a class="page-link page-item page-current" href="?page={{ page }}{{ additional_url_query }}">{{ page }}</a>
        {% else %}
          <a class="page-link page-item" href="?page={{ page }}{{ additional_url_query }}">{{ page }}</a>
        {% endif %}
      {% endfor %}

      {% if pagination_range.last_page_out_of_range %}
        <span class="page-item">...</span>
        <a class="page-link page-item" href="?page={{ pagination_range.total_pages }}{{ additional_url_query }}">{{ pagination_range.total_pages }}</a>
      {% endif %}    
    </div>
  </div>
{% endif %}

books/templates/books/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="{% url 'books:search' %}" method="GET" class="search-form">
            <input type="search" class="search-input" name="q" value="{{ search_term }}" required
            placeholder="Busque por um livro">
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>